
# Rule "mvn-clean-install:monitor"
.PHONY: mvn-clean-install\:monitor
mvn-clean-install\:monitor:
	@for f in *; do \
		if [ -f $${f}/pom.xml ]; then \
			echo $$f; \
			echo "==================================="; \
			if grep -q "<id>monitoring</id>" "$${f}/pom.xml" ; then \
				cd $$f && mvn clean install -Pmonitoring && cd ..; \
			else \
				cd $$f && mvn clean install && cd ..; \
			fi ; \
			echo " "; \
		fi \
	done
