
# Rule "docker-build-perfmon"
.PHONY: docker-build-perfmon
docker-build-perfmon:
	@for f in *; do \
		if [ -d $${f}/docker ]; then \
			echo $$f; \
			echo "==================================="; \
			if grep -q "perfmon" "$${f}/docker/Makefile" ; then \
				cd $$f/docker && make build:perfmon && cd ../..; \
			else ; \
				cd $$f/docker && make build:local && cd ../..; \
			fi \
			echo " "; \
		fi \
	done
