
# Rule "gitstaging"
.PHONY: gitstaging
gitstaging:
	@for f in *; do \
                if [ -d $${f}/.git ]; then \
                        echo $$f; \
                        echo "==================================="; \
                        cd $$f && git checkout staging || true && cd ..; \
                        echo " "; \
                fi \
        done
