
# Rule "gitstatus"
.PHONY: gitstatus
gitstatus:
	@for f in *; do \
		if [ -d $${f}/.git ]; then \
			echo $$f; \
			echo "==================================="; \
			cd $$f && git status && cd ..; \
			echo " "; \
		fi \
	done
