
# Rule "gitbranch"
.PHONY: gitbranch
gitbranch:
	@for f in *; do \
		if [ -d $${f}/.git ]; then \
			echo $$f; \
			echo "==================================="; \
			cd $$f; \
			var=$$(git branch | grep "*"); \
			echo "$$var"; \
			cd ..; \
			echo ""; \
		fi \
	done
