
# Rule "gitmaster"
.PHONY: gitmaster
gitmaster:
	@for f in *; do \
                if [ -d $${f}/.git ]; then \
                        echo $$f; \
                        echo "==================================="; \
                        cd $$f && git checkout master && cd ..; \
                        echo " "; \
                fi \
        done
