
# Rule "gitdevelop"
.PHONY: gitdevelop
gitdevelop:
	@for f in *; do \
                if [ -d $${f}/.git ]; then \
                        echo $$f; \
                        echo "==================================="; \
                        cd $$f && git checkout develop || true && cd ..; \
                        echo " "; \
                fi \
        done
