
# Rule "gitpull"
.PHONY: gitpull
gitpull:
	@for f in *; do \
		if [ -d $${f}/.git ]; then \
			echo $$f; \
			echo "==================================="; \
			cd $$f && git pull || true && cd ..; \
			echo " "; \
		fi \
	done
